name: Build custom_rasterizer CUDA wheel (Python 3.11, Linux)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential ninja-build
          python -m pip install --upgrade pip setuptools wheel numpy torch

      - name: Set up CUDA environment
        run: |
          echo "export CUDA_HOME=/usr/local/cuda" >> $GITHUB_ENV
          echo "/usr/local/cuda/bin" >> $GITHUB_PATH

      - name: Build the CUDA wheel
        run: |
          python setup.py bdist_wheel

      - name: Upload wheel
        uses: actions/upload-artifact@v4
        with:
          name: custom_rasterizer-cuda-wheel
          path: dist/*.whl
