name: Build custom_rasterizer CUDA wheel (Python 3.11, Linux)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: nvidia/cuda:11.8.0-cudnn8-devel-ubuntu22.04  # CUDA 11.8 base
    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Python 3.11
        run: |
          apt-get update
          apt-get install -y python3.11 python3.11-dev python3-pip build-essential ninja-build

      - name: Install PyTorch with CUDA 11.8
        run: |
          python3.11 -m pip install --upgrade pip setuptools wheel
          python3.11 -m pip install torch==2.0.1+cu118 torchvision==0.15.2+cu118 --index-url https://download.pytorch.org/whl/cu118

      - name: Build the CUDA wheel
        run: |
          export CUDA_HOME=/usr/local/cuda-11.8  # Explicit CUDA 11.8 path
          export PATH=/usr/local/cuda-11.8/bin:$PATH
          python3.11 setup.py bdist_wheel

      - name: Upload wheel
        uses: actions/upload-artifact@v4
        with:
          name: custom_rasterizer-cuda-wheel
          path: custom_rasterizer/dist/*.whl
