name: Build custom_rasterizer wheel (Python 3.11, PyTorch 2.7.0)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: nvidia/cuda:12.1.1-devel-ubuntu22.04  # Matches PyTorch's CUDA 12.1
    defaults:
      run:
        shell: bash

    steps:
      - name: Install system dependencies
        run: |
          apt-get update
          apt-get install -y git python3.11 python3.11-dev python3-pip \
            build-essential ninja-build binutils unzip patchelf
          ln -s /usr/bin/python3.11 /usr/bin/python

      - name: Clone repository
        run: |
          git clone --recurse-submodules https://github.com/Adhi-Git-hub/custom_rasterizer_wheel.git .
          ls -la

      - name: Install exact PyTorch version
        run: |
          python -m pip install --upgrade pip setuptools wheel
          python -m pip install torch==2.7.0+cu121 torchvision==0.17.0+cu121 \
            --index-url https://download.pytorch.org/whl/cu121

      - name: Configure dynamic linking correctly
        run: |
          # Set RPATH to find PyTorch libraries
          export LD_RUN_PATH=/usr/local/lib/python3.11/dist-packages/torch/lib:$LD_RUN_PATH
          export CFLAGS="-L/usr/local/lib/python3.11/dist-packages/torch/lib"
          export LDFLAGS="-Wl,-rpath,/usr/local/lib/python3.11/dist-packages/torch/lib"

      - name: Build the wheel
        run: |
          export CUDA_HOME=/usr/local/cuda
          export PATH=/usr/local/cuda/bin:$PATH
          export TORCH_CUDA_ARCH_LIST="8.0"  # Tesla T4
          export FORCE_CUDA=1
          export MAX_JOBS=4
          
          python setup.py clean --all
          python setup.py bdist_wheel --verbose

      - name: Verify wheel
        run: |
          mkdir -p tmp_inspect
          unzip -d tmp_inspect dist/*.whl
          
          echo "=== Critical Checks ==="
          find tmp_inspect -name "*.so" -exec sh -c '
            echo "\nInspecting $1:"
            patchelf --print-rpath "$1"
            ldd "$1" | grep -i "torch\|cuda" || echo "No Torch/CUDA dependencies"
            objdump -p "$1" | grep -A10 NEEDED
          ' sh {} \;

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: custom_rasterizer-torch2.7-cuda12.1
          path: dist/*.whl
