name: Build custom_rasterizer wheel for Python 3.11 (Linux)

on:
  workflow_dispatch:

jobs:
  build-wheel:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel

      - name: Build wheel
        run: |
          python setup.py bdist_wheel

      - name: Upload wheel as artifact
        uses: actions/upload-artifact@v3
        with:
          name: custom_rasterizer-wheel
          path: dist/*.whl
