name: Build custom_rasterizer CUDA wheel (Python 3.11, Linux)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: nvidia/cuda:11.8.0-cudnn8-devel-ubuntu22.04
    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          apt-get update
          apt-get install -y python3 python3-pip python3-dev build-essential
          pip3 install --upgrade pip setuptools wheel numpy torch

      - name: Build the CUDA wheel
        run: |
          export CUDA_HOME=/usr/local/cuda
          python3 setup.py bdist_wheel

      - name: Upload wheel
        uses: actions/upload-artifact@v4
        with:
          name: custom_rasterizer-cuda-wheel
          path: dist/*.whl
