name: Build custom_rasterizer wheel (Python 3.11, PyTorch 2.2.0)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: nvidia/cuda:12.5.0-devel-ubuntu22.04
    defaults:
      run:
        shell: bash

    steps:
      - name: Install system dependencies
        run: |
          apt-get update
          apt-get install -y git python3.11 python3.11-dev python3-pip \
            build-essential ninja-build binutils unzip patchelf
          ln -s /usr/bin/python3.11 /usr/bin/python

      - name: Clone repository
        run: |
          git clone --recurse-submodules https://github.com/Adhi-Git-hub/custom_rasterizer_wheel.git .
          ls -la

      - name: Install PyTorch 2.2.0 with CUDA 12.1
        run: |
          python -m pip install --upgrade pip setuptools wheel
          python -m pip install torch==2.2.0+cu121 torchvision==0.17.0+cu121 \
            --index-url https://download.pytorch.org/whl/cu121

      - name: Patch for CUDA compatibility
        run: |
          find . -type f \( -name "*.cpp" -o -name "*.cu" -o -name "*.h" -o -name "*.pyx" \) \
            -exec sed -i 's/11\.0/12.6/g' {} +
          find . -type f \( -name "*.cpp" -o -name "*.cu" -o -name "*.h" -o -name "*.pyx" \) \
            -exec sed -i 's/110/126/g' {} +

      - name: Build the wheel
        run: |
          export CUDA_HOME=/usr/local/cuda
          export PATH=/usr/local/cuda/bin:$PATH
          export TORCH_CUDA_ARCH_LIST="8.0"
          export FORCE_CUDA=1
          export MAX_JOBS=4
          
          python setup.py clean --all
          python setup.py bdist_wheel --verbose

      - name: Verify wheel compatibility
        run: |
          mkdir -p tmp_inspect
          unzip -d tmp_inspect dist/*.whl
          
          find tmp_inspect -name "*.so" -exec sh -c '
            echo "\nChecking: $1"
            ldd "$1" | grep -i "libtorch\|cuda" || true
            objdump -p "$1" | grep -A5 NEEDED
          ' sh {} \;

      - name: Upload wheel
        uses: actions/upload-artifact@v4
        with:
          name: custom_rasterizer-torch220-cuda121
          path: dist/*.whl
          retention-days: 7
