name: Build custom_rasterizer wheel (Python 3.11, PyTorch 2.7.0, CUDA 12.6)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: nvidia/cuda:12.6.2-devel-ubuntu22.04  # CUDA 12.6 build env (safe for Colab)
    defaults:
      run:
        shell: bash

    steps:
      - name: Install system dependencies
        run: |
          apt-get update
          apt-get install -y git python3.11 python3.11-dev python3-pip \
                             ninja-build unzip patchelf build-essential
          ln -sf /usr/bin/python3.11 /usr/bin/python

      - name: Clone repo
        run: |
          git clone --recurse-submodules https://github.com/Adhi-Git-hub/custom_rasterizer_wheel.git .
          ls -la

      - name: Install PyTorch 2.7.0 + cu126
        run: |
          python -m pip install --upgrade pip setuptools wheel
          python -m pip install torch==2.7.0+cu126 torchvision==0.22.0+cu126 \
            --index-url https://download.pytorch.org/whl/cu126

      - name: Build the wheel
        run: |
          export CUDA_HOME=/usr/local/cuda
          export PATH=$CUDA_HOME/bin:$PATH
          export FORCE_CUDA=1
          export MAX_JOBS=4
          export TORCH_CUDA_ARCH_LIST="8.0"

          python setup.py clean --all
          python setup.py bdist_wheel --verbose

      - name: Verify .so dependencies
        run: |
          mkdir -p tmp_inspect
          unzip -d tmp_inspect dist/*.whl
          echo "🔍 ldd on .so:"
          find tmp_inspect -name "*.so" -exec ldd {} \;

      - name: Upload wheel
        uses: actions/upload-artifact@v4
        with:
          name: custom_rasterizer-cu126
          path: dist/*.whl
