name: Build custom_rasterizer wheel (Python 3.11, CUDA 12.5)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: nvidia/cuda:12.5.0-cudnn8-devel-ubuntu22.04
    defaults:
      run:
        shell: bash

    steps:
      - name: Install Git and manually clone repo (with submodules)
        run: |
          apt-get update
          apt-get install -y git
          git clone --recurse-submodules https://github.com/Adhi-Git-hub/custom_rasterizer_wheel.git .
          ls -la

      - name: Install Python 3.11 and build tools
        run: |
          apt-get install -y python3.11 python3.11-dev python3-pip build-essential ninja-build
          ln -s /usr/bin/python3.11 /usr/bin/python

      - name: Install PyTorch with CUDA 12.5 (cu125)
        run: |
          python -m pip install --upgrade pip setuptools wheel
          python -m pip install torch==2.3.0+cu125 torchvision==0.18.0+cu125 --index-url https://download.pytorch.org/whl/cu125

      - name: Build the CUDA wheel
        run: |
          export CUDA_HOME=/usr/local/cuda
          export PATH=/usr/local/cuda/bin:$PATH
          export TORCH_CUDA_ARCH_LIST="8.0"
          export FORCE_CUDA=1

          ls -la lib/custom_rasterizer_kernel/
          python setup.py bdist_wheel

      - name: Upload wheel
        uses: actions/upload-artifact@v4
        with:
          name: custom_rasterizer-wheel
          path: dist/*.whl
